-- WC 2026 venue seed: official stadium + host city per fixture, sourced from the
-- published schedule (Wikipedia/FIFA) and cross-verified. Run once; the sync never
-- writes these columns, so the values persist. Idempotent.
update matches set venue='Estadio Azteca', city='Mexico City' where id=537327;
update matches set venue='Estadio Akron', city='Guadalajara' where id=537328;
update matches set venue='BMO Field', city='Toronto' where id=537333;
update matches set venue='SoFi Stadium', city='Los Angeles' where id=537345;
update matches set venue='Levi''s Stadium', city='San Francisco Bay Area' where id=537334;
update matches set venue='MetLife Stadium', city='New York/New Jersey' where id=537339;
update matches set venue='Gillette Stadium', city='Boston' where id=537340;
update matches set venue='BC Place', city='Vancouver' where id=537346;
update matches set venue='NRG Stadium', city='Houston' where id=537351;
update matches set venue='AT&T Stadium', city='Dallas' where id=537357;
update matches set venue='Lincoln Financial Field', city='Philadelphia' where id=537352;
update matches set venue='Estadio BBVA', city='Monterrey' where id=537358;
update matches set venue='Mercedes-Benz Stadium', city='Atlanta' where id=537369;
update matches set venue='Lumen Field', city='Seattle' where id=537363;
update matches set venue='Hard Rock Stadium', city='Miami' where id=537370;
update matches set venue='SoFi Stadium', city='Los Angeles' where id=537364;
update matches set venue='MetLife Stadium', city='New York/New Jersey' where id=537391;
update matches set venue='Gillette Stadium', city='Boston' where id=537392;
update matches set venue='Arrowhead Stadium', city='Kansas City' where id=537397;
update matches set venue='Levi''s Stadium', city='San Francisco Bay Area' where id=537398;
update matches set venue='NRG Stadium', city='Houston' where id=537403;
update matches set venue='AT&T Stadium', city='Dallas' where id=537409;
update matches set venue='BMO Field', city='Toronto' where id=537410;
update matches set venue='Estadio Azteca', city='Mexico City' where id=537404;
update matches set venue='Mercedes-Benz Stadium', city='Atlanta' where id=537329;
update matches set venue='SoFi Stadium', city='Los Angeles' where id=537335;
update matches set venue='BC Place', city='Vancouver' where id=537336;
update matches set venue='Estadio Akron', city='Guadalajara' where id=537330;
update matches set venue='Lumen Field', city='Seattle' where id=537348;
update matches set venue='Gillette Stadium', city='Boston' where id=537342;
update matches set venue='Lincoln Financial Field', city='Philadelphia' where id=537341;
update matches set venue='Levi''s Stadium', city='San Francisco Bay Area' where id=537347;
update matches set venue='NRG Stadium', city='Houston' where id=537359;
update matches set venue='BMO Field', city='Toronto' where id=537353;
update matches set venue='Arrowhead Stadium', city='Kansas City' where id=537354;
update matches set venue='Estadio BBVA', city='Monterrey' where id=537360;
update matches set venue='Mercedes-Benz Stadium', city='Atlanta' where id=537371;
update matches set venue='SoFi Stadium', city='Los Angeles' where id=537365;
update matches set venue='Hard Rock Stadium', city='Miami' where id=537372;
update matches set venue='BC Place', city='Vancouver' where id=537366;
update matches set venue='AT&T Stadium', city='Dallas' where id=537399;
update matches set venue='Lincoln Financial Field', city='Philadelphia' where id=537393;
update matches set venue='MetLife Stadium', city='New York/New Jersey' where id=537394;
update matches set venue='Levi''s Stadium', city='San Francisco Bay Area' where id=537400;
update matches set venue='NRG Stadium', city='Houston' where id=537405;
update matches set venue='Gillette Stadium', city='Boston' where id=537411;
update matches set venue='BMO Field', city='Toronto' where id=537412;
update matches set venue='Estadio Akron', city='Guadalajara' where id=537406;
update matches set venue='Lumen Field', city='Seattle' where id=537338;
update matches set venue='BC Place', city='Vancouver' where id=537337;
update matches set venue='Hard Rock Stadium', city='Miami' where id=537343;
update matches set venue='Mercedes-Benz Stadium', city='Atlanta' where id=537344;
update matches set venue='Estadio Azteca', city='Mexico City' where id=537331;
update matches set venue='Estadio BBVA', city='Monterrey' where id=537332;
update matches set venue='MetLife Stadium', city='New York/New Jersey' where id=537355;
update matches set venue='Lincoln Financial Field', city='Philadelphia' where id=537356;
update matches set venue='AT&T Stadium', city='Dallas' where id=537362;
update matches set venue='Arrowhead Stadium', city='Kansas City' where id=537361;
update matches set venue='SoFi Stadium', city='Los Angeles' where id=537349;
update matches set venue='Levi''s Stadium', city='San Francisco Bay Area' where id=537350;
update matches set venue='Gillette Stadium', city='Boston' where id=537395;
update matches set venue='BMO Field', city='Toronto' where id=537396;
update matches set venue='Estadio Akron', city='Guadalajara' where id=537373;
update matches set venue='NRG Stadium', city='Houston' where id=537374;
update matches set venue='BC Place', city='Vancouver' where id=537367;
update matches set venue='Lumen Field', city='Seattle' where id=537368;
update matches set venue='Lincoln Financial Field', city='Philadelphia' where id=537414;
update matches set venue='MetLife Stadium', city='New York/New Jersey' where id=537413;
update matches set venue='Hard Rock Stadium', city='Miami' where id=537407;
update matches set venue='Mercedes-Benz Stadium', city='Atlanta' where id=537408;
update matches set venue='Arrowhead Stadium', city='Kansas City' where id=537402;
update matches set venue='AT&T Stadium', city='Dallas' where id=537401;
update matches set venue='SoFi Stadium', city='Los Angeles' where id=537417;
update matches set venue='NRG Stadium', city='Houston' where id=537423;
update matches set venue='Gillette Stadium', city='Boston' where id=537415;
update matches set venue='Estadio BBVA', city='Monterrey' where id=537418;
update matches set venue='AT&T Stadium', city='Dallas' where id=537424;
update matches set venue='MetLife Stadium', city='New York/New Jersey' where id=537416;
update matches set venue='Estadio Azteca', city='Mexico City' where id=537425;
update matches set venue='Mercedes-Benz Stadium', city='Atlanta' where id=537426;
update matches set venue='Lumen Field', city='Seattle' where id=537422;
update matches set venue='Levi''s Stadium', city='San Francisco Bay Area' where id=537421;
update matches set venue='SoFi Stadium', city='Los Angeles' where id=537420;
update matches set venue='BMO Field', city='Toronto' where id=537419;
update matches set venue='BC Place', city='Vancouver' where id=537429;
update matches set venue='AT&T Stadium', city='Dallas' where id=537428;
update matches set venue='Hard Rock Stadium', city='Miami' where id=537427;
update matches set venue='Arrowhead Stadium', city='Kansas City' where id=537430;
update matches set venue='NRG Stadium', city='Houston' where id=537376;
update matches set venue='Lincoln Financial Field', city='Philadelphia' where id=537375;
update matches set venue='MetLife Stadium', city='New York/New Jersey' where id=537377;
update matches set venue='Estadio Azteca', city='Mexico City' where id=537378;
update matches set venue='AT&T Stadium', city='Dallas' where id=537379;
update matches set venue='Lumen Field', city='Seattle' where id=537380;
update matches set venue='Mercedes-Benz Stadium', city='Atlanta' where id=537381;
update matches set venue='BC Place', city='Vancouver' where id=537382;
update matches set venue='Gillette Stadium', city='Boston' where id=537383;
update matches set venue='SoFi Stadium', city='Los Angeles' where id=537384;
update matches set venue='Hard Rock Stadium', city='Miami' where id=537385;
update matches set venue='Arrowhead Stadium', city='Kansas City' where id=537386;
update matches set venue='AT&T Stadium', city='Dallas' where id=537387;
update matches set venue='Mercedes-Benz Stadium', city='Atlanta' where id=537388;
update matches set venue='Hard Rock Stadium', city='Miami' where id=537389;
update matches set venue='MetLife Stadium', city='New York/New Jersey' where id=537390;